import Head from "next/head";
import Image from "next/image";
import Sidebar from "../src/components/Sidebar";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Sidebar></Sidebar>
          <div>2</div>
        </main>
      </div>
      <style jsx>
        {`
          main {
            display: grid;
            width: 100%;
            height: 100vh;
            grid-template-columns: 500px 1fr;
            
          }
          @media (min-width: 320px) {
            main {
              grid-template-columns: 1fr;
              
            }
            @media (min-width: 980px)  {
              main {
                grid-template-columns: 400px 1fr;
               
              }
              @media (min-width: 1220px)  {
                main {
                  grid-template-columns: 500px 1fr;
                 
                }
          }


        `}
      </style>
    </>
  );
}
